run:
  timeout: 3m
  modules-download-mode: readonly

linters:
  enable:
    - errcheck
    - govet
    - staticcheck
    - unused
    - gosimple
    - ineffassign
    - typecheck
    - misspell
    - gofmt
    - goimports

linters-settings:
  govet:
    enable-all: true
    disable:
      - fieldalignment
  misspell:
    locale: US

issues:
  max-issues-per-linter: 50
  max-same-issues: 5
  exclude-dirs:
    - vendor
    - third_party
